# Generated by Django 5.1.3 on 2024-11-27 22:00

import colorfield.fields
import core.models.fields.string
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', core.models.fields.string.StringField(blank=True)),
                ('bg_color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None)),
                ('txt_color', colorfield.fields.ColorField(blank=True, default='#000000', image_field=None, max_length=25, samples=None)),
            ],
            options={
                'verbose_name': 'Task Status',
                'verbose_name_plural': 'Task Statuses',
                'db_table': 'task_status',
            },
        ),
    ]
