# Generated by Django 5.1.3 on 2024-11-29 17:08

import core.models.fields.string
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_taskcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', core.models.fields.string.StringField()),
            ],
            options={
                'verbose_name': 'Task Note',
                'verbose_name_plural': 'Task Notes',
                'db_table': 'task_note',
            },
        ),
    ]
