# Generated by Django 5.1.3 on 2024-11-29 17:19

import core.models.fields.string
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tasknote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('priority', core.models.fields.string.StringField(blank=True, choices=[('highest', 'Highest'), ('high', 'High'), ('low', 'Low'), ('lowest', 'Lowest')], null=True)),
                ('order', models.IntegerField()),
                ('is_complete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Subtask',
                'verbose_name_plural': 'Subtasks',
                'db_table': 'subtask',
            },
        ),
    ]
